apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: timetable-planner-be-prod
resources:
- namespace.yaml
- secret.yaml
- ../../../base/be

images:
- name: scgskku/timetable-planner-be
  newName: scgskku/timetable-planner-be-prod
- name: scgskku/timetable-planner-be-prod
  newName: scgskku/timetable-planner-be-prod
  newTag: d0bf2422cd520cd3c1da744b14627e0b003ef7cb
