apiVersion: v1
kind: Secret
metadata:
  name: timetable-planner-be-secret
  annotations:
    avp.kubernetes.io/path: kv/data/timetable-planner-be-prod-secret
type: Opaque
stringData:
  COURSEPLANNER_DB_URL: <path:kv/data/timetable-planner-be-prod-secret#prod-db-url>
  COURSEPLANNER_DB_USERNAME: <path:kv/data/timetable-planner-be-prod-secret#prod-db-username>
  COURSEPLANNER_DB_PASSWORD: <path:kv/data/timetable-planner-be-prod-secret#prod-db-password>
  JWT_SECRET: <path:kv/data/timetable-planner-be-prod-secret#prod-jwt-secret>
  GOOGLE_CLIENT_ID: <path:kv/data/timetable-planner-be-prod-secret#prod-google-client-id>
  GOOGLE_CLIENT_SECRET: <path:kv/data/timetable-planner-be-prod-secret#prod-google-client-secret>
  REDIS_HOST: timetable-planner-redis-service
  REDIS_PORT: "6379"
  MCP_OAUTH_CLIENT_SECRET: <path:kv/data/timetable-planner-be-prod-secret#prod-mcp-oauth-client-secret>
  REDIS_PASSWORD: <path:kv/data/timetable-planner-redis-prod-secret#prod-redis-password>
  EVERYTIME_COOKIE: <path:kv/data/timetable-planner-redis-prod-secret#prod-everytime-cookie>
  EVERYTIME_COOKIE_ENCRYPTION_SECRET: <path:kv/data/timetable-planner-redis-prod-secret#prod-everytime-cookie-secret>