apiVersion: v1
kind: Secret
metadata:
  name: timetable-planner-be-secret
  annotations:
    avp.kubernetes.io/path: kv/data/timetable-planner-be-prod-secret
type: Opaque
stringData:
  TEMP_VALUE: <path:kv/data/timetable-planner-be-prod-secret#temp-value>
  REDIS_HOST: timetable-planner-redis-service
  REDIS_PORT: "6379"
  REDIS_PASSWORD: <path:kv/data/timetable-planner-redis-prod-secret#prod-redis-password>
