apiVersion: v1
kind: Secret
metadata:
  name: timetable-planner-redis-secret
  annotations:
    avp.kubernetes.io/path: kv/data/timetable-planner-redis-dev-secret
type: Opaque
stringData:
  REDIS_PASSWORD: <path:kv/data/timetable-planner-redis-dev-secret#dev-redis-password>
