apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: timetable-planner-dev
resources:
- secret.yaml
- ../../../base/be

patches:
- path: ingress-patch.json
  target:
    kind: Ingress
    name: timetable-planner-be-ingress
    
images:
- name: scgskku/timetable-planner-be
  newName: scgskku/timetable-planner-be-dev
  newTag: 05fc289c1bddd29f7a160715d302a8b186f93762
