apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: timetable-planner-dev
resources:
- secret.yaml
- ../../../base/be

patches:
- path: ingress-patch.json
  target:
    kind: Ingress
    name: timetable-planner-be-ingress
    
images:
- name: scgskku/timetable-planner-be
  newName: scgskku/timetable-planner-be-dev
  newTag: 113297ff4daab79bfd203c0f1ae8a936b52c9004
