apiVersion: v1
kind: Secret
metadata:
  name: timetable-planner-be-secret
  annotations:
    avp.kubernetes.io/path: kv/data/timetable-planner-be-dev-secret
type: Opaque
stringData:
  TEMP_VALUE: <path:kv/data/timetable-planner-be-dev-secret#temp-value>
