apiVersion: v1
kind: Secret
metadata:
  name: timetable-planner-be-secret
  annotations:
    avp.kubernetes.io/path: kv/data/timetable-planner-be-dev-secret
type: Opaque
stringData:
  COURSEPLANNER_DB_URL: <path:kv/data/timetable-planner-be-dev-secret#dev-db-url>
  COURSEPLANNER_DB_USERNAME: <path:kv/data/timetable-planner-be-dev-secret#dev-db-username>
  COURSEPLANNER_DB_PASSWORD: <path:kv/data/timetable-planner-be-dev-secret#dev-db-password>
  JWT_SECRET: <path:kv/data/timetable-planner-be-dev-secret#dev-jwt-secret>
  GOOGLE_CLIENT_ID: <path:kv/data/timetable-planner-be-dev-secret#dev-google-client-id>
  GOOGLE_CLIENT_SECRET: <path:kv/data/timetable-planner-be-dev-secret#dev-google-client-secret>

  

