apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: timetable-planner-prod
resources:
- ../../../base/fe

images:
- name: scgskku/timetable-planner-fe
  newName: scgskku/timetable-planner-fe-prod
- name: scgskku/timetable-planner-fe-prod
  newTag: 3be2d574d56e224a6b111f33ca7e97f4466e43e0
