apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: timetable-planner-prod
resources:
- ../../../base/fe

images:
- name: scgskku/timetable-planner-fe
  newName: scgskku/timetable-planner-fe-prod
- name: scgskku/timetable-planner-fe-prod
  newTag: ff75bd694bd0ee7062872565f8e0a01f3c53813a
