apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: timetable-planner-prod
resources:
- ../../../base/fe

images:
- name: scgskku/timetable-planner-fe
  newName: scgskku/timetable-planner-fe-prod
- name: scgskku/timetable-planner-fe-prod
  newTag: 2868e9104a4a7468d44a8fbf32618ba462bcaa35
