apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: timetable-planner-dev
resources:
- ../../../base/fe

patches:
- path: ingress-patch.json
  target:
    kind: Ingress
    name: timetable-planner-fe-ingress

images:
- name: scgskku/timetable-planner-fe
  newName: scgskku/timetable-planner-fe-dev
  newTag: a059c20f42be035b21a647440b5f75379fcc52b4
- name: scgskku/timetable-planner-fe-dev
  newTag: 2c34d2113ed37b6a7d35d66f7d2665a59669bd8c
