apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: timetable-planner-fe-dev
resources:
  - namespace.yaml
  - ../../base/fe

patches:
  - path: ingress-patch.json
    target:
      kind: Ingress
      name: timetable-planner-fe-ingress

images:
  - name: scgskku/timetable-planner-fe
    newName: scgskku/timetable-planner-fe-dev
  - name: scgskku/timetable-planner-fe-dev
    newTag: thisistemporarytag
