apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: timetable-planner-dev
resources:
- ../../../base/fe

patches:
- path: ingress-patch.json
  target:
    kind: Ingress
    name: timetable-planner-fe-ingress

images:
- name: scgskku/timetable-planner-fe
  newName: scgskku/timetable-planner-fe-dev
- name: scgskku/timetable-planner-fe-dev
  newTag: 24a01441bd349c35990e21ce5e6c8f92ac0e6d54
